Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - '**/*.rb'

Style/SpecialGlobalVars:
  Exclude:
    - 'simple-jsonapi-deserializer.gemspec'
